Choice.create(text: "Instant Messaging, Peer-to-Peer (P2P) applications", correct: false, question_id: 1)
Choice.create(text: "Malware - virus, worms, spyware", correct: false, question_id: 1)
Choice.create(text: "Spam, Phishing attacks", correct: false, question_id: 1)
Choice.create(text: "End Users", correct: true, question_id: 1)
Choice.create(text: "Always wear your security badge when leaving work, even if just for a break. They should be worn outside of the office in public so other people know where you work.", correct: true, question_id: 2)
Choice.create(text: "Control access to your office by ensuring the door closes completely behind when entering and exiting. Ensure that no one slips in behind you.", correct: false, question_id: 2)
Choice.create(text: "When working in a public setting, prevent shoulder surfing by shielding your paperwork and keyboard from view using your body.", correct: false, question_id: 2)
Choice.create(text: "Follow the Clear Desk and Screen Policy. Store confidential and sensitive items in a secure place.", correct: false, question_id: 2)
Choice.create(text: "Do not reply to the message.", correct: false, question_id: 3)
Choice.create(text: "Click the link so you can see what the site looks like.", correct: true, question_id: 3)
Choice.create(text: "Keep your system up to date, and install up-to-date antivirus and anti-spyware software.", correct: false, question_id: 3)
Choice.create(text: "Report the phishing email to the legitimate company or organization that has been spoofed.", correct: false, question_id: 3)
Choice.create(text: "Avoid", correct: false, question_id: 4)
Choice.create(text: "Recognize", correct: true, question_id: 4)
Choice.create(text: "Challenge", correct: false, question_id: 4)
Choice.create(text: "Log", correct: false, question_id: 4)
Choice.create(text: "Spyware or Adware installation", correct: false, question_id: 5)
Choice.create(text: "Browser Hijacking", correct: false, question_id: 5)
Choice.create(text: "Information or identity theft", correct: false, question_id: 5)
Choice.create(text: "All of the above", correct: true, question_id: 5)
Choice.create(text: "Do not give out computer or network information.", correct: false, question_id: 6)
Choice.create(text: "Do not complete confidential company tasks in an insecure setting.", correct: false, question_id: 6)
Choice.create(text: "Do not secure sensitive documents and media.", correct: true, question_id: 6)
Choice.create(text: "Do not give out personal identifiable information.", correct: false, question_id: 6)
Choice.create(text: "A program that is secretly installed onto your computer and makes copies of itself which consumes your computer resources.", correct: true, question_id: 7)
Choice.create(text: "A program that protects your computer from hackers.", correct: false, question_id: 7)
Choice.create(text: "A program that is installed onto your computer that monitors your internet use.", correct: false, question_id: 7)
Choice.create(text: "All of the above", correct: false, question_id: 7)
Choice.create(text: "Phishing attacks", correct: false, question_id: 8)
Choice.create(text: "Virus attacks", correct: false, question_id: 8)
Choice.create(text: "Spyware", correct: false, question_id: 8)
Choice.create(text: "All of the above ", correct: true, question_id: 8)
Choice.create(text: "Never email personal information ", correct: true, question_id: 9)
Choice.create(text: "Send out price lists for your home-based business products", correct: false, question_id: 9)
Choice.create(text: "Forward inspirational and humorous emails to your co-workers to brighten their day", correct: false, question_id: 9)
Choice.create(text: "Send an email to all your friends and co-workers to advertise a job opening in your area", correct: false, question_id: 9)
Choice.create(text: "Instant Message", correct: false, question_id: 10)
Choice.create(text: "Internet download", correct: false, question_id: 10)
Choice.create(text: "Portable media", correct: false, question_id: 10)
Choice.create(text: "Email ", correct: true, question_id: 10)
Choice.create(text: "Helps protect individuals from being victims of security incidents.", correct: false, question_id: 11)
Choice.create(text: "Provides an understanding of steps to follow in the event of a security incident", correct: false, question_id: 11)
Choice.create(text: "Helps to understand levels of responsibility", correct: false, question_id: 11)
Choice.create(text: "All of the above ", correct: true, question_id: 11)
Choice.create(text: "Urgent request from your manager with unexpected attachment", correct: false, question_id: 12)
Choice.create(text: "Request from your bank with a link to update information", correct: false, question_id: 12)
Choice.create(text: "Email from unknown sender with seemingly random email address", correct: false, question_id: 12)
Choice.create(text: "None of the above", correct: true, question_id: 12)
Choice.create(text: "The data files under 'My Documents' folder in my office desktop will be automatically backup and protected by IT administrators.", correct: false, question_id: 13)
Choice.create(text: "Using look-alike substitutions of numbers or symbols", correct: false, question_id: 13)
Choice.create(text: "A combination of upper and lowercase letters mixed with numbers and symbols", correct: true, question_id: 13)
Choice.create(text: "Using common names or words from the dictionary", correct: false, question_id: 13)
Choice.create(text: "I can download my payroll data and similar data sets onto a public laptop, as long as I delete it later.", correct: false, question_id: 14)
Choice.create(text: "As the data owner, I should grant others access to the data on an 'as needed' basis, and keep current records of who has access to the data while it is in possession.", correct: true, question_id: 14)
Choice.create(text: "I will leave my desk only 2 minutes (for example get some water in pantry), so I do not need to log off my computer", correct: false, question_id: 14)
Choice.create(text: "For the sake of convenience, I retain my data in multiple places.", correct: false, question_id: 14)
Choice.create(text: "Network intrusions, hacks, malware (viruses)", correct: false, question_id: 15)
Choice.create(text: "Rogue employee or contractor", correct: false, question_id: 15)
Choice.create(text: "Improper disposal, loss, missing or theft", correct: false, question_id: 15)
Choice.create(text: "All of the above", correct: true, question_id: 15)
Choice.create(text: "Cyber-security is network security only (anti-virus, firewall)", correct: false, question_id: 16)
Choice.create(text: "Cybersecurity is all about audit and compliance", correct: false, question_id: 16)
Choice.create(text: "Cybersecurity is not a business roadblock", correct: true, question_id: 16)
Choice.create(text: "Cybersecurity is equal to physical security", correct: false, question_id: 16)
Choice.create(text: "Piggyback", correct: false, question_id: 17)
Choice.create(text: "Identity Theft", correct: true, question_id: 17)
Choice.create(text: "Water Holing", correct: false, question_id: 17)
Choice.create(text: "Spear Phishing", correct: false, question_id: 17)
Choice.create(text: "Baiting", correct: false, question_id: 18)
Choice.create(text: "Pretexting", correct: false, question_id: 18)
Choice.create(text: "Phone phishing", correct: true, question_id: 18)
Choice.create(text: "Phishing", correct: false, question_id: 18)
Choice.create(text: "Diversion Theft", correct: false, question_id: 19)
Choice.create(text: "Water Holing", correct: true, question_id: 19)
Choice.create(text: "Baiting", correct: false, question_id: 19)
Choice.create(text: "Pretexting", correct: false, question_id: 19)
Choice.create(text: "Pretexting", correct: false, question_id: 20)
Choice.create(text: "Tailgating", correct: true, question_id: 20)
Choice.create(text: "Phishing", correct: false, question_id: 20)
Choice.create(text: "Diversion Theft", correct: false, question_id: 20)
Choice.create(text: "Fill the form then click 'Send' button.", correct: false, question_id: 21)
Choice.create(text: "Ignore the email.", correct: false, question_id: 21)
Choice.create(text: "Delete the email without clicking.", correct: false, question_id: 21)
Choice.create(text: "Contact the Cybersecurity team. ", correct: true, question_id: 21)
Choice.create(text: "Phishing", correct: false, question_id: 22)
Choice.create(text: "Water Holing.", correct: false, question_id: 22)
Choice.create(text: "Tailgating", correct: false, question_id: 22)
Choice.create(text: "Pretexting", correct: true, question_id: 22)
