Question.create(id: 1, text: 'What is the biggest vulnerability to computer information security?', category: 'Cyber Security Awareness Training')
Question.create(id: 2, text: 'All of these are good physical security practices except?', category: 'Cyber Security Awareness Training')
Question.create(id: 3, text: 'What should you do if you think the email you received is a phishing attempt except?', category: 'Cyber Security Awareness Training')
Question.create(id: 4, text: 'The first step in Security Awareness is being able to ________ a security threat.', category: 'Cyber Security Awareness Training')
Question.create(id: 5, text: 'If you are not careful about your Internet browsing, which of the following can result?', category: 'Cyber Security Awareness Training')
Question.create(id: 6, text: 'Which of the following is a counter-measure to prevent social engineering attack, except:', category: 'Cyber Security Awareness Training')
Question.create(id: 7, text: 'Which statement most accurately describes virus?', category: 'Cyber Security Awareness Training')
Question.create(id: 8, text: 'A malicious user can rely on email or webpage to launch a ____?', category: 'Cyber Security Awareness Training')
Question.create(id: 9, text: 'Which of the following is a proper use of email?', category: 'Cyber Security Awareness Training')
Question.create(id: 10, text: 'What is the most common delivery method for viruses?', category: 'Cyber Security Awareness Training')
Question.create(id: 11, text: 'Why is it important to have a good understanding of Cyber Security policies and procedures?', category: 'Cyber Security Awareness Training')
Question.create(id: 12, text: 'Which of the following circumstances should you treat as NOT suspicious?', category: 'Cyber Security Awareness Training')
Question.create(id: 13, text: 'Which of the following is a good way to create a password?', category: 'Cyber Security Awareness Training')
Question.create(id: 14, text: 'Which action may NOT cause data breach?', category: 'Cyber Security Awareness Training')
Question.create(id: 15, text: 'Which type of incident belongs to cyber security threats?', category: 'Cyber Security Awareness Training')
Question.create(id: 16, text: 'Which conception is Correct about cyber security?', category: 'Cyber Security Awareness Training')
Question.create(id: 17, text: 'Which of the followings is NOT a common Social Engineering techniques?', category: 'Cyber Security Awareness Training')
Question.create(id: 18, text: "The following statement best describes which attacking technique: Attacker uses a rogue Interactive Voice Response (IVR) system to recreate a legitimate-sounding copy of a bank or other institution's IVR system. The victim is prompted to call in to the 'bank' via a (ideally toll free) number provided in order to 'verify' information.", category: 'Cyber Security Awareness Training')
Question.create(id: 19, text: 'The following best describe which attack: The victim is a particular group (organization, industry, or region). In this attack, the attacker guesses or observes which websites the group often uses and infects one or more of them with malware. Common techniques involve hijacking legitimate, trusted sites to push malware to unsuspecting users.', category: 'Cyber Security Awareness Training')
Question.create(id: 20, text: 'The following best describe which attack: An attacker, seeking entry to a restricted area secured by unattended, electronic access control, e.g. by RFID card, simply walks in behind a person who has legitimate access.', category: 'Cyber Security Awareness Training')
Question.create(id: 21, text: "You open an email or text, and see a message like this: 'We suspect an unauthorized transaction on your account. To ensure that your account is not compromised, please fill out the following form to confirm your identity.' Which following is the most appropriate action you should take?", category: 'Cyber Security Awareness Training')
Question.create(id: 22, text: 'The following best describe which attack: Attacker present himself (herself) as someone else, in order to obtain trust or private information.', category: 'Cyber Security Awareness Training')
